### ISSUE TITLE
Import Courses from XML

### ISSUE THREAD

**Issue by BullshitPingu** [mobileappdevhm/cie-server-team-2#20]
Courses are now importable from xml.

**Comment by BullshitPingu** [comment]
The xmls:
- https://www.hm.edu/2/en/course_offerings/courses_in_english/cietables/app/xml_ss_18.en.xml
- https://www.hm.edu/2/en/course_offerings/courses_in_english/cietables/app/xml_ws_18_19.en.xml

**Comment by BullshitPingu** [comment]
Unfortunately they seem to not even include the title in those xml files. Thus the files are not quite useful.
Impeded until the xml files get at least course titles for each course.

**Comment by gsocher** [comment]
Thanks for finding this bug. I am asking the CMS provider to add the Title and correct the URL of the course description.

**Comment by BullshitPingu** [comment]
Should work now!

Useful Tool for converting PDFs to Markdown to parse the pdfs: https://github.com/jzillmann/pdf-to-markdown

**Comment by BullshitPingu** [comment]
REST API does support importing it now.. Need to implement it as well in the management interface.

**Comment by BullshitPingu** [comment]
Its in.
