### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by BullshitPingu** [mobileappdevhm/cie-server-team-2#30]
In case the password has been forgotten by a user we need to have possibility to reset the password.

**Comment by BullshitPingu** [comment]
How would we send E-Mails to users?
Can we get access to the university mail server?

**Comment by gsocher** [comment]
We can not access the university mail server. You can set up a Postfix SMTP outgoing mail server on cie.cs.hm.edu.

**Comment by BullshitPingu** [comment]
Implemented using sendgrid.
