### ISSUE TITLE
Add Image and address to Campus

### ISSUE THREAD

**Issue by VoitreX** [mobileappdevhm/cie-server-team-2#32]
Add Image and address to Campus

/*
class Campus {
  final int id;
  final String name;
  final String image;
  final String address;

  const Campus(this.id, this.name, this.image, this.address);

  Map<String, dynamic> toMap() {
    Map<String, dynamic> tempMap = new Map();
    tempMap["id"] = this.id;
    tempMap["name"] = this.name;
    tempMap["image"] = this.image;
    tempMap["address"] = this.address;
    return tempMap;
  }
}
*/

This is what the class looks like in the app. I disagree with this though I think the images should be stored locally. its going to make lookup times very **slow**

**Comment by BullshitPingu** [comment]
Duplicate: https://github.com/mobileappdevhm/cie-server-team-2/issues/28
