### ISSUE TITLE
Add CIE to USER

### ISSUE THREAD

**Issue by VoitreX** [mobileappdevhm/cie-server-team-2#33]
add a set of CIEs that the User has put in their CIEs.

below is the class of CIE I have made for the app.

class Cie {
  int id = -1;
  final String name;
  final double ects;
  final String lecturerName;
  final int department;
  final String description;

  Cie(this.name, this.department, this.lecturerName, this.ects,
      this.description,
      [this.id]);

  Map<String, dynamic> toMap() {
    Map<String, dynamic> tempMap = new Map();
    tempMap["id"] = this.id;
    tempMap["name"] = this.name;
    tempMap["department"] = this.department;
    tempMap["lecturerName"] = this.lecturerName;
    tempMap["ects"] = this.ects;
    tempMap["description"] = this.description;
    return tempMap;
  }

  Map<String, dynamic> toMapNoId() {
    Map<String, dynamic> tempMap = new Map();
    tempMap["name"] = this.name;
    tempMap["department"] = this.department;
    tempMap["lecturerName"] = this.lecturerName;
    tempMap["ects"] = this.ects;
    tempMap["description"] = this.description;
    return tempMap;
  }
}

**Comment by BullshitPingu** [comment]
Let's keep that one for Sprint 3 as we need to investigate further on how to do this. I'm kind of reluctant to add this kind of information to the server since I'd like to save the courses just by their id..

For now it may be better to just store it locally.

**Comment by BullshitPingu** [comment]
Closes. Should be only stored locally.
