### ISSUE TITLE
Make Web Application GDPR Compliant

### ISSUE THREAD

**Issue by BullshitPingu** [mobileappdevhm/cie-server-team-2#38]
Try to make web application GDPR compliant. Somehow. Maybe use a template.

**Comment by l0renor** [comment]
Privacy policy
1.	Introduction
	This privacy policy informs you about the way the CiE-Server handles personal
data.
2. 	person responsible 
	Hochschule für angewandte Wissenschaften München,
Körperschaft des öffentlichen Rechts, vertreten durch den Präsidenten,
Prof. Dr. Martin Leitner 
Lothstraße 34
D-80335 München
Tel.: +49 (0) 89 12 65 - 0
Fax: +49 (0) 89 12 65 - 3000
Email: presse@hm.edu
Internet: www.hm.edu
3. 	contact 
Prof. Dr. Gudrun Socher	
Fakultät für Informatik und Mathematik
Lothstraße 64
D-80335 München
gudrun.socher@hm.edu
4.	types of stored data
•	Your e-mail address
•	 Your selected courses
•	Your favorized courses
•	 the courses you take  

5.	affected persons
We store the data of the users of our app mainly students of the Hochschule München, exchange students as well as professors using the CiE App/Server.
6.	purpose of processing
We process your data to provide you with information about the Courses in English offer as well as providing you with the allocated to you.
7.	duration of storage
All our data is stored as long as the user uses  the CiE servicres.
 

8. right of objection
You can stop further processing of you data according to Art. 21 DSGVO by contacting the CiE contact person.

**Comment by l0renor** [comment]
sag wenn ich noch was ändern soll i

**Comment by BullshitPingu** [comment]
It is in the settings.
